services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_psql
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql
    restart: always

volumes:
  postgres-volume: